language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - '12.14'

deploy:
  provider: script
  script: npm run deploy
  cleanup: true
  on:
    branch: master

dist: bionic
os: linux
