language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - '10.0'

deploy:
  provider: script
  script: npm run deploy
  cleanup: false
  on:
    branch: master

dist: bionic
os: linux
