name: Build, Test and Deploy to Github Pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build
      run: |
        npm ci
        npm run build --if-present

    - name: Test
      if: success()
      run: |
        npm run test --if-present
        npm run linter --if-present

    - name: Deploy
      if: success() && github.ref=='master'
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
        BUILD_SCRIPT: npm ci && npm run build
